### ISSUE TITLE
hotend-flow-tester.netlify.app has been broken for ~2 weeks

### ISSUE THREAD

**Issue by fstd** [iFallUpHill/flow-calculator#11]
Tried to send you an email about it, hopefully you'll see it here.

The site does not load; could you please take a look at what's going on?

**Comment by iFallUpHill** [comment]
Works on my end from a couple different locations. 
Are you seeing any errors in the console?

**Comment by fstd** [comment]
You are right, it works in an incognito window, so I guess my browser's cache is corrupted.

Thanks, and sorry for the false alarm.
