### ISSUE TITLE
Add GitHub discussions to repository

### ISSUE THREAD

**Issue by Kaloszer** [iFallUpHill/flow-calculator#16]
Simply enable github discussions:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository

To the repository so we can share ideas instead of having to create github issues whereas they're not necessarily issues :).

**Comment by iFallUpHill** [comment]
I'll keep this in mind but for now I'll leave discussions disabled as I don't feel that they're necessary.
