### ISSUE TITLE
GCode for Cooling fan is not correct

### ISSUE THREAD

**Issue by unitrix0** [iFallUpHill/flow-calculator#21]
If I set "Fan Speed" to 40% it creates:
`M106 S40 ; Set Fan Speed`

But according to the [Marlin documentation](https://marlinfw.org/docs/gcode/M106.html) `S` is a value from 0 to 255. So it should be 255*0.4 => 102

besides that, great tool :)

**Comment by iFallUpHill** [comment]
Hey, thanks for reporting! I fixed this in the default gcode by multiplying the fanSpeed value by 255/100 in the example startcode.

https://github.com/iFallUpHill/flow-calculator/commit/1b12988fded2eaa3f56232fb0e1c35b9e981b974
