### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [iFallUpHill/flow-calculator#4]
Would be nice if it was possible to save all settings in local storage or cookie.

Is this something that could be added?

**Comment by iFallUpHill** [comment]
Every change is currently saved to localstorage by default.

**Comment by 4e576rt8uh9ij9okp** [comment]
That's weird, when I closed the website it had some default numbers in it. Maybe a extension is messing something up.

**Comment by 4e576rt8uh9ij9okp** [comment]
I don't know what was the issue but it works now... could be an extension or something no idea.
